apiVersion: v1
kind: Service
metadata:
  labels:
    app: udaconnect-location-ingester-svc
  name: udaconnect-location-ingester-svc
spec:
  ports:
  - name: 5005-5005
    nodePort: 30005
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: udaconnect-location-ingester-svc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udaconnect-location-ingester-svc
  name: udaconnect-location-ingester-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-location-ingester-svc
  template:
    metadata:
      labels:
        app: udaconnect-location-ingester-svc
    spec:
      containers:
      - image: masrayie/udaconnect-location-ingester-svc:v.2.0
        name: udaconnect-location-ingester-svc
        imagePullPolicy: Always
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
      restartPolicy: Always
